-- Script de creación de la estructura de base de datos relacional para Supabase.
-- Ejecuta esta consulta en el SQL Editor de tu nuevo proyecto de Supabase.

-- 1. Tabla de Supermercados
create table if not exists public.supermercados (
  id text primary key,
  nombre text not null,
  logo_url text,
  color_hex text,
  activo boolean default true not null
);

-- Precargar supermercados iniciales
insert into public.supermercados (id, nombre, color_hex) values
  ('mercadona', 'Mercadona', '#00A859'),
  ('eroski', 'Eroski', '#005CA9'),
  ('dia', 'Dia', '#E2001A'),
  ('aldi', 'Aldi', '#002C5B'),
  ('carrefour', 'Carrefour', '#003893')
on conflict (id) do nothing;

-- 2. Tabla de Categorías Unificadas
create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nombre text not null unique
);

-- Precargar categorías iniciales comunes
insert into public.categorias (nombre) values
  ('Lácteos'),
  ('Panadería'),
  ('Conservas y Aceites'),
  ('Dulces y Chocolates'),
  ('Frutas y Verduras')
on conflict (nombre) do nothing;

-- 3. Tabla de Productos Adaptada
drop table if exists public.productos;
create table public.productos (
  id bigint generated by default as identity primary key,
  referencia_id text not null,
  nombre text not null,
  precio numeric(10, 2) not null,
  supermercado_id text references public.supermercados(id) on delete cascade not null,
  categoria_id bigint references public.categorias(id) on delete set null,
  last_seen timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  ean text,
  kcal numeric(8, 2),
  proteinas numeric(8, 2),
  carbohidratos numeric(8, 2),
  grasas numeric(8, 2),
  constraint productos_supermercado_referencia_unique unique (supermercado_id, referencia_id)
);

-- Habilitar Row Level Security (RLS) en todas las tablas
alter table public.supermercados enable row level security;
alter table public.categorias enable row level security;
alter table public.productos enable row level security;

-- 1. Políticas para supermercados
create policy "Permitir lectura pública de supermercados" 
  on public.supermercados for select to anon, authenticated using (true);

create policy "Permitir gestión completa de supermercados" 
  on public.supermercados for all to anon, authenticated using (true) with check (true);

-- 2. Políticas para categorías
create policy "Permitir lectura pública de categorías" 
  on public.categorias for select to anon, authenticated using (true);

create policy "Permitir gestión completa de categorías" 
  on public.categorias for all to anon, authenticated using (true) with check (true);

-- 3. Políticas para productos
create policy "Permitir lectura pública de productos" 
  on public.productos for select to anon, authenticated using (true);

create policy "Permitir gestión completa de productos" 
  on public.productos for all to anon, authenticated using (true) with check (true);

-- 4. Tabla de Historial de Precios
create table if not exists public.historial_precios (
  id bigint generated by default as identity primary key,
  supermercado_id text references public.supermercados(id) on delete cascade not null,
  referencia_id text not null,
  precio numeric(10, 2) not null,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS para historial
alter table public.historial_precios enable row level security;

create policy "Permitir lectura pública de historial" 
  on public.historial_precios for select to anon, authenticated using (true);

create policy "Permitir gestión completa de historial" 
  on public.historial_precios for all to anon, authenticated using (true) with check (true);

-- Función para registrar cambios históricos
create or replace function public.registrar_historial_precio()
returns trigger as $$
begin
  if (tg_op = 'INSERT') or (tg_op = 'UPDATE' and old.precio <> new.precio) then
    insert into public.historial_precios (supermercado_id, referencia_id, precio)
    values (new.supermercado_id, new.referencia_id, new.precio);
  end if;
  return new;
end;
$$ language plpgsql security definer;

-- Trigger sobre productos
drop trigger if exists on_producto_price_changed on public.productos;
create trigger on_producto_price_changed
  after insert or update on public.productos
  for each row execute procedure public.registrar_historial_precio();

-- Migración: añadir columnas de EAN y macros si la tabla ya existe
-- Ejecuta solo este bloque si ya tienes la tabla creada previamente
alter table public.productos add column if not exists ean text;
alter table public.productos add column if not exists kcal numeric(8, 2);
alter table public.productos add column if not exists proteinas numeric(8, 2);
alter table public.productos add column if not exists carbohidratos numeric(8, 2);
alter table public.productos add column if not exists grasas numeric(8, 2);
